using UnityEngine;
using Cinemachine;

public class CameraFollow : MonoBehaviour
{
    public GameObject target; // Objeto al que la c치mara debe seguir
    private CinemachineVirtualCamera virtualCamera; // Referencia al componente CinemachineVirtualCamera

    private void Start()
    {
        virtualCamera = GetComponent<CinemachineVirtualCamera>();
    }

    private void LateUpdate()
    {
        if (target != null)
        {
            // Actualizar la posici칩n de seguimiento de la c치mara para que coincida con la posici칩n del objetivo
            virtualCamera.Follow = target.transform;
        }
    }
}

